before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -w -s
      - -X "github.com/fgouteroux/slam/version.PlatformName={{.Os}}/{{.Arch}}"
      - -X "github.com/fgouteroux/slam/version.GitCommit={{.Commit}}"
      - -X "github.com/fgouteroux/slam/version.BuildTime={{.Date}}"
      - -X "github.com/fgouteroux/slam/version.Version={{.Version}}"
    goarch:
      - amd64

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
